import { Article } from '../models/article.model';

export const ARTICLES: Article[] = [
  {
    title: 'Tips Pajak UMKM di Era Digital',
    author: 'Eko Nugroho',
    date: '2025-07-20',
    summary:
      'Bagaimana UMKM bisa memanfaatkan teknologi untuk pelaporan pajak yang lebih mudah dan efisien.',
    img: './images/courses/courseone.webp',
    link: '/articles/tips-pajak-umkm',
    category: 'UMKM',
  },
  {
    title: 'Perubahan Regulasi Pajak 2025',
    author: 'Dewi Anggraini',
    date: '2025-07-19',
    summary:
      'Ringkasan perubahan regulasi pajak terbaru dan dampaknya bagi pelaku usaha.',
    img: './images/courses/coursetwo.webp',
    link: '/articles/regulasi-2025',
    category: 'Pajak',
  },
  {
    title: 'Strategi Akuntansi untuk Startup',
    author: 'Budi Santoso',
    date: '2025-07-18',
    summary:
      'Strategi akuntansi yang tepat untuk startup agar tetap comply dan efisien.',
    img: './images/courses/coursethree.webp',
    link: '/articles/akuntansi-startup',
    category: 'Akuntansi',
  },
  {
    title: 'Cara Efektif Lapor Pajak Online',
    author: 'Rina Wijaya',
    date: '2025-07-17',
    summary: 'Panduan praktis lapor pajak online untuk pelaku UMKM.',
    img: './images/courses/courseone.webp',
    link: '/articles/lapor-pajak-online',
    category: 'Pajak',
  },
  {
    title: 'UMKM Go Digital: Tantangan & Solusi',
    author: 'Andi Pratama',
    date: '2025-07-16',
    summary: 'Solusi digital untuk UMKM agar lebih kompetitif.',
    img: './images/courses/coursetwo.webp',
    link: '/articles/umkm-go-digital',
    category: 'UMKM',
  },
  {
    title: 'Akuntansi Dasar untuk Pebisnis',
    author: 'Siti Lestari',
    date: '2025-07-15',
    summary: 'Dasar-dasar akuntansi yang wajib diketahui pebisnis.',
    img: './images/courses/coursethree.webp',
    link: '/articles/akuntansi-dasar-pebisnis',
    category: 'Akuntansi',
  },
  {
    title: 'Pajak Startup: Apa yang Harus Diperhatikan?',
    author: 'Eko Nugroho',
    date: '2025-07-14',
    summary: 'Hal penting pajak untuk startup baru.',
    img: './images/courses/courseone.webp',
    link: '/articles/pajak-startup',
    category: 'Startup',
  },
  {
    title: 'Mengenal Pajak Penghasilan Pribadi',
    author: 'Dewi Anggraini',
    date: '2025-07-13',
    summary: 'Penjelasan pajak penghasilan untuk individu.',
    img: './images/courses/coursetwo.webp',
    link: '/articles/pajak-penghasilan-pribadi',
    category: 'Pajak',
  },
  {
    title: 'Tips Akuntansi untuk Freelancer',
    author: 'Budi Santoso',
    date: '2025-07-12',
    summary: 'Tips akuntansi praktis untuk freelancer.',
    img: './images/courses/coursethree.webp',
    link: '/articles/akuntansi-freelancer',
    category: 'Akuntansi',
  },
  {
    title: 'Regulasi Pajak Baru 2025',
    author: 'Rina Wijaya',
    date: '2025-07-11',
    summary: 'Update regulasi pajak terbaru tahun 2025.',
    img: './images/courses/courseone.webp',
    link: '/articles/regulasi-pajak-baru-2025',
    category: 'Pajak',
  },
  {
    title: 'Strategi Bisnis UMKM Modern',
    author: 'Andi Pratama',
    date: '2025-07-10',
    summary: 'Strategi bisnis modern untuk UMKM.',
    img: './images/courses/coursetwo.webp',
    link: '/articles/strategi-bisnis-umkm',
    category: 'UMKM',
  },
  {
    title: 'Pentingnya Audit untuk Startup',
    author: 'Siti Lestari',
    date: '2025-07-09',
    summary: 'Kenapa audit penting untuk startup.',
    img: './images/courses/coursethree.webp',
    link: '/articles/audit-startup',
    category: 'Startup',
  },
  {
    title: 'Perencanaan Pajak Akhir Tahun',
    author: 'Eko Nugroho',
    date: '2025-07-08',
    summary: 'Tips perencanaan pajak menjelang akhir tahun.',
    img: './images/courses/courseone.webp',
    link: '/articles/perencanaan-pajak-akhir-tahun',
    category: 'Pajak',
  },
  {
    title: 'Akuntansi UMKM: Langkah Awal',
    author: 'Dewi Anggraini',
    date: '2025-07-07',
    summary: 'Langkah awal akuntansi untuk UMKM.',
    img: './images/courses/coursetwo.webp',
    link: '/articles/akuntansi-umkm',
    category: 'UMKM',
  },
  {
    title: 'Pajak Digital: Update Terbaru',
    author: 'Budi Santoso',
    date: '2025-07-06',
    summary: 'Update terbaru pajak digital di Indonesia.',
    img: './images/courses/coursethree.webp',
    link: '/articles/pajak-digital',
    category: 'Pajak',
  },
  {
    title: 'Manajemen Keuangan Startup',
    author: 'Rina Wijaya',
    date: '2025-07-05',
    summary: 'Manajemen keuangan untuk startup.',
    img: './images/courses/courseone.webp',
    link: '/articles/manajemen-keuangan-startup',
    category: 'Startup',
  },
  {
    title: 'UMKM dan Pajak Digital',
    author: 'Andi Pratama',
    date: '2025-07-04',
    summary: 'UMKM dan tantangan pajak digital.',
    img: './images/courses/coursetwo.webp',
    link: '/articles/umkm-pajak-digital',
    category: 'UMKM',
  },
  {
    title: 'Akuntansi Pajak untuk Pemula',
    author: 'Siti Lestari',
    date: '2025-07-03',
    summary: 'Panduan akuntansi pajak untuk pemula.',
    img: './images/courses/coursethree.webp',
    link: '/articles/akuntansi-pajak-pemula',
    category: 'Akuntansi',
  },
  {
    title: 'Tips Efisiensi Pajak Bisnis',
    author: 'Eko Nugroho',
    date: '2025-07-02',
    summary: 'Tips efisiensi pajak untuk bisnis.',
    img: './images/courses/courseone.webp',
    link: '/articles/efisiensi-pajak-bisnis',
    category: 'Pajak',
  },
  {
    title: 'Pajak & Akuntansi: Sinergi Bisnis',
    author: 'Dewi Anggraini',
    date: '2025-07-01',
    summary: 'Sinergi pajak dan akuntansi untuk bisnis.',
    img: './images/courses/coursetwo.webp',
    link: '/articles/pajak-akuntansi-sinergi',
    category: 'Akuntansi',
  },
];
