export const COURSES_DATA = [
  {
    slug: 'tips-pajak-umkm-digital',
    title: 'Tips Pajak UMKM di Era Digital',
    author: 'Eko Nugroho',
    date: '2025-07-20',
    summary:
      'Bagaimana UMKM bisa memanfaatkan teknologi untuk pelaporan pajak yang lebih mudah dan efisien.',
    img: './images/courses/courseone.png',
    alt: 'Tips Pajak UMKM',
    badge: 'UMKM',
    rating: '4.8',
    price: 'Gratis',
    classes: 8,
    participants: 1200,
  },
  {
    slug: 'regulasi-pajak-2025',
    title: 'Perubahan Regulasi Pajak 2025',
    author: 'Dewi Anggraini',
    date: '2025-07-15',
    summary:
      'Ringkasan perubahan regulasi pajak terbaru dan dampaknya bagi pelaku usaha.',
    img: './images/courses/coursetwo.png',
    alt: 'Regulasi Pajak 2025',
    badge: 'Regulasi',
    rating: '4.7',
    price: 'Rp 150.000',
    classes: 6,
    participants: 950,
  },
  {
    slug: 'akuntansi-startup',
    title: 'Strategi Akuntansi untuk Startup',
    author: 'Budi Santoso',
    date: '2025-07-10',
    summary:
      'Strategi akuntansi yang tepat untuk startup agar tetap comply dan efisien.',
    img: './images/courses/coursethree.png',
    alt: 'Akuntansi Startup',
    badge: 'Startup',
    rating: '4.9',
    price: 'Rp 200.000',
    classes: 7,
    participants: 800,
  },
  {
    slug: 'kursus-pajak-pribadi',
    title: 'Kursus Pajak Pribadi',
    author: 'Rina Sari',
    date: '2025-07-05',
    summary: 'Pelajari cara mengelola pajak pribadi dengan mudah dan benar.',
    img: './images/courses/courseone.png',
    alt: 'Pajak Pribadi',
    badge: 'Pribadi',
    rating: '4.6',
    price: 'Rp 100.000',
    classes: 5,
    participants: 600,
  },
  {
    slug: 'pajak-freelancer',
    title: 'Pajak untuk Freelancer',
    author: 'Andi Wijaya',
    date: '2025-06-28',
    summary: 'Panduan lengkap pajak untuk pekerja lepas dan freelancer.',
    img: './images/courses/coursetwo.png',
    alt: 'Pajak Freelancer',
    badge: 'Freelancer',
    rating: '4.5',
    price: 'Gratis',
    classes: 4,
    participants: 400,
  },
  {
    slug: 'umkm-lanjutan',
    title: 'Pajak UMKM Lanjutan',
    author: 'Eko Nugroho',
    date: '2025-06-20',
    summary: 'Materi lanjutan untuk UMKM yang ingin naik kelas.',
    img: './images/courses/coursethree.png',
    alt: 'UMKM Lanjutan',
    badge: 'UMKM',
    rating: '4.8',
    price: 'Rp 120.000',
    classes: 7,
    participants: 700,
  },
  {
    slug: 'pajak-internasional-pebisnis',
    title: 'Pajak Internasional untuk Pebisnis',
    author: 'Siti Rahma',
    date: '2025-06-10',
    summary: 'Dasar-dasar pajak internasional untuk ekspansi bisnis.',
    img: './images/courses/courseone.png',
    alt: 'Pajak Internasional',
    badge: 'Internasional',
    rating: '4.7',
    price: 'Rp 250.000',
    classes: 9,
    participants: 500,
  },
  {
    slug: 'audit-pajak-modern',
    title: 'Audit Pajak Modern',
    author: 'Dian Pratama',
    date: '2025-05-30',
    summary: 'Teknik audit pajak terbaru untuk perusahaan.',
    img: './images/courses/coursetwo.png',
    alt: 'Audit Pajak',
    badge: 'Audit',
    rating: '4.6',
    price: 'Rp 180.000',
    classes: 7,
    participants: 350,
  },
  {
    slug: 'pajak-digital-economy',
    title: 'Pajak Digital Economy',
    author: 'Rudi Hartono',
    date: '2025-05-20',
    summary: 'Pajak di era ekonomi digital dan e-commerce.',
    img: './images/courses/coursethree.png',
    alt: 'Pajak Digital',
    badge: 'Digital',
    rating: '4.8',
    price: 'Rp 220.000',
    classes: 8,
    participants: 420,
  },
  {
    slug: 'manajemen-pajak-perusahaan',
    title: 'Manajemen Pajak Perusahaan',
    author: 'Linda Kusuma',
    date: '2025-05-10',
    summary: 'Strategi manajemen pajak untuk perusahaan besar.',
    img: './images/courses/courseone.png',
    alt: 'Manajemen Pajak',
    badge: 'Manajemen',
    rating: '4.9',
    price: 'Rp 300.000',
    classes: 12,
    participants: 800,
  },
  {
    slug: 'pajak-properti-real-estate',
    title: 'Pajak Properti & Real Estate',
    author: 'Tono Suprapto',
    date: '2025-04-30',
    summary: 'Panduan pajak properti dan real estate di Indonesia.',
    img: './images/courses/coursetwo.png',
    alt: 'Pajak Properti',
    badge: 'Properti',
    rating: '4.7',
    price: 'Rp 170.000',
    classes: 6,
    participants: 300,
  },
  {
    slug: 'pajak-kendaraan-transportasi',
    title: 'Pajak Kendaraan & Transportasi',
    author: 'Yuni Astuti',
    date: '2025-04-20',
    summary: 'Cara mengelola pajak kendaraan dan transportasi.',
    img: './images/courses/coursethree.png',
    alt: 'Pajak Kendaraan',
    badge: 'Transportasi',
    rating: '4.5',
    price: 'Rp 110.000',
    classes: 5,
    participants: 250,
  },
  {
    slug: 'pajak-warisan-hibah',
    title: 'Pajak Warisan & Hibah',
    author: 'Agus Setiawan',
    date: '2025-04-10',
    summary: 'Pajak atas warisan dan hibah di Indonesia.',
    img: './images/courses/courseone.png',
    alt: 'Pajak Warisan',
    badge: 'Warisan',
    rating: '4.6',
    price: 'Rp 130.000',
    classes: 4,
    participants: 180,
  },
  {
    slug: 'pajak-sektor-kreatif',
    title: 'Pajak Sektor Kreatif',
    author: 'Maya Putri',
    date: '2025-03-30',
    summary: 'Pajak untuk pelaku industri kreatif dan seni.',
    img: './images/courses/coursetwo.png',
    alt: 'Pajak Kreatif',
    badge: 'Kreatif',
    rating: '4.8',
    price: 'Rp 160.000',
    classes: 7,
    participants: 320,
  },
  {
    slug: 'umkm-pemula',
    title: 'Pajak UMKM Pemula',
    author: 'Eko Nugroho',
    date: '2025-03-20',
    summary: 'Materi pajak dasar untuk UMKM baru.',
    img: './images/courses/coursethree.png',
    alt: 'UMKM Pemula',
    badge: 'UMKM',
    rating: '4.7',
    price: 'Rp 90.000',
    classes: 3,
    participants: 150,
  },
  {
    slug: 'startup-lanjutan',
    title: 'Pajak Startup Lanjutan',
    author: 'Budi Santoso',
    date: '2025-03-10',
    summary: 'Materi lanjutan pajak untuk startup berkembang.',
    img: './images/courses/courseone.png',
    alt: 'Startup Lanjutan',
    badge: 'Startup',
    rating: '4.9',
    price: 'Rp 210.000',
    classes: 9,
    participants: 400,
  },
  {
    slug: 'freelancer-lanjutan',
    title: 'Pajak Freelancer Lanjutan',
    author: 'Andi Wijaya',
    date: '2025-02-28',
    summary: 'Tips pajak lanjutan untuk freelancer profesional.',
    img: './images/courses/coursetwo.png',
    alt: 'Freelancer Lanjutan',
    badge: 'Freelancer',
    rating: '4.6',
    price: 'Rp 140.000',
    classes: 5,
    participants: 220,
  },
  {
    slug: 'pribadi-lanjutan',
    title: 'Pajak Pribadi Lanjutan',
    author: 'Rina Sari',
    date: '2025-02-20',
    summary: 'Materi lanjutan pajak pribadi untuk individu.',
    img: './images/courses/coursethree.png',
    alt: 'Pribadi Lanjutan',
    badge: 'Pribadi',
    rating: '4.7',
    price: 'Rp 120.000',
    classes: 6,
    participants: 180,
  },
  {
    slug: 'umkm-digital',
    title: 'Pajak UMKM Digital',
    author: 'Eko Nugroho',
    date: '2025-02-10',
    summary: 'UMKM go digital: pajak dan pelaporan online.',
    img: './images/courses/courseone.png',
    alt: 'UMKM Digital',
    badge: 'UMKM',
    rating: '4.8',
    price: 'Rp 100.000',
    classes: 4,
    participants: 200,
  },
  {
    slug: 'startup-pemula',
    title: 'Pajak Startup Pemula',
    author: 'Budi Santoso',
    date: '2025-01-30',
    summary: 'Dasar-dasar pajak untuk startup baru.',
    img: './images/courses/coursetwo.png',
    alt: 'Startup Pemula',
    badge: 'Startup',
    rating: '4.8',
    price: 'Rp 100.000',
    classes: 4,
    participants: 120,
  },
  {
    slug: 'freelancer-pemula',
    title: 'Pajak Freelancer Pemula',
    author: 'Andi Wijaya',
    date: '2025-01-20',
    summary: 'Panduan pajak dasar untuk freelancer baru.',
    img: './images/courses/coursethree.png',
    alt: 'Freelancer Pemula',
    badge: 'Freelancer',
    rating: '4.7',
    price: 'Rp 80.000',
    classes: 2,
    participants: 100,
  },
];
