name: Deploy Angular App to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration=production

      - name: Deploy to VPS via rsync
        uses: easingthemes/ssh-deploy@v4
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          TARGET: /var/www/angular-app
          SOURCE: dist/nac-angular
          EXCLUDE: .git
          ARGS: -avz --delete
          SCRIPT_AFTER: |
            cd /var/www/angular-app
            sudo chown -R www-data:www-data /var/www/angular-app
            sudo chmod -R 755 /var/www/angular-app
            sudo systemctl reload nginx
